server:
  port: 8081
  servlet:
    context-path: /shop
#  上传图片会创建一个临时文件，这里指定为/data/apps/temp这个目录
  tomcat:
    basedir: /data/apps/temp

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url:  jdbc:mysql://localhost:3306/shop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB